# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'work' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for work
 pod 'Firebase/Core'
 pod 'Firebase/Firestore'
 pod 'FirebaseFirestoreSwift'
 pod 'Firebase/Storage'
 pod 'FirebaseUI/Storage'
 pod 'Google-Mobile-Ads-SDK'
end
